---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/app-menu: development
    fabric8.io/git-commit: f7967da2069f486a3e6dbef233574eccac3e0dae
    fabric8.io/scm-con-url: scm:git:git@github.com:uberops/ubermonitoring.git/george-hipchat
    fabric8.io/scm-url: http://github.com/uberops/ubermonitoring/george-hipchat
    fabric8.io/iconUrl: https://github.com/uberops/george-hipchat/raw/master/logo.png
    fabric8.io/git-branch: release-v1.0.0
    fabric8.io/scm-devcon-url: scm:git:git@github.com:uberops/ubermonitoring.git/george-hipchat
    fabric8.io/scm-tag: ubermonitoring-secops-1.0.0
  labels:
    provider: ubermonitoring
    expose: "true"
    project: george-hipchat
    version: 1.0.0
    group: io.ubermonitoring.secops.apps
  name: george-hipchat
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: george-hipchat
    project: george-hipchat
    provider: ubermoniotring
    group: io.ubermonitoring.secops.apps
