---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    fabric8.io/git-commit: f7967da2069f486a3e6dbef233574eccac3e0dae
    fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2.327
    fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
    fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/hubot-slack
    fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
    fabric8.io/git-branch: release-v2.2.327
    fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
    fabric8.io/scm-tag: fabric8-devops-2.0.1
  labels:
    name: hubot-slack
    provider: fabric8
    project: hubot-slack
    version: 2.2.327
    group: io.fabric8.devops.apps
  name: hubot-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hubot-slack
      project: hubot-slack
      provider: fabric8
      version: 2.2.327
      group: io.fabric8.devops.apps
  template:
    metadata:
      annotations:
        fabric8.io/git-commit: f7967da2069f486a3e6dbef233574eccac3e0dae
        fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=hubot-slack&var-version=2.2.327
        fabric8.io/scm-con-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
        fabric8.io/scm-url: http://github.com/fabric8io/fabric8-devops/hubot-slack
        fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-devops/master/hubot-slack/src/main/fabric8/icon.png
        fabric8.io/git-branch: release-v2.2.327
        fabric8.io/scm-devcon-url: scm:git:git@github.com:fabric8io/fabric8-devops.git/hubot-slack
        fabric8.io/scm-tag: fabric8-devops-2.0.1
      labels:
        name: hubot-slack
        provider: fabric8
        project: hubot-slack
        version: 2.2.327
        group: io.fabric8.devops.apps
      name: hubot-slack
    spec:
      containers:
      - env:
        - name: HUBOT_GRAFANA_API_KEY
          valueFrom:
            configMapKeyRef:
              key: hubot-grafana-api-key
              name: hubot-slack
        - name: HUBOT_SLACK_TOKEN
          valueFrom:
            configMapKeyRef:
              key: hubot-slack-token
              name: hubot-slack
        - name: HUBOT_GRAFANA_HOST
          valueFrom:
            configMapKeyRef:
              key: hubot-grafana-host
              name: hubot-slack
        - name: HUBOT_JENKINS_URL
          valueFrom:
            configMapKeyRef:
              key: hubot-jenkins-url
              name: hubot-slack
        image: fabric8/hubot-slack:2.2.327
        name: hubot-slack
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
